katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import delete
from todolist.views import done
from todolist.views import show_todolist_ajax
from todolist.views import submit_ajax, show_json

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='createtask'),
    path('delete/<int:id>/', delete, name='delete'),
    path('done/<int:id>/', done, name='done'),
    path('ajax/', show_todolist_ajax, name='show_todolist_ajax'),
    path('/submit', submit_ajax, name='submit_ajax'),
    path('/json', show_json, name='show_json'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class todolistItem(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField()
    done = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import todolistItem

class taskform(forms.ModelForm):
    class Meta:
        model = todolistItem
        fields = {"title", "description"}

todolist/views.py
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from todolist.models import todolistItem
from todolist.forms import taskform
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = todolistItem.objects.all().filter(user=request.user)
    context = {
    'list_data': data_todolist,
    'nama': 'Rizka Nisrina Nabila',
    'npm': '2106653344',
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    context = {
        'nama': 'Rizka Nisrina Nabila',
        'npm': '2106653344',
    }
    return render(request, "todolist_ajax.html", context)

@login_required(login_url='/todolist/login/')
def submit_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        
        new_data = todolistItem(user=request.user, title=title, description=description, date=datetime.datetime.now())
        new_data.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

def show_json(request):
    data = todolistItem.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data))

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist_ajax"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def create_task(request):
    if request.method == "POST":
        form = taskform(request.POST)
        form.instance.user = request.user
        form.instance.date = datetime.datetime.now()
        if form.is_valid():
            form.save()
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            return response
    else:
        form = taskform()

    context = {'form':form}
    return render(request, 'createtask.html', context)

def delete(request, id):
    data = todolistItem.objects.get(id=id)
    data.delete()
    return redirect('todolist:show_todolist')

def done(request, id):
    data = todolistItem.objects.get(id=id)
    if data.done == False:
        data.done = True
    else:
        data.done = False
    data.save()
    return redirect('todolist:show_todolist')

todolist/templates/createtask.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}  

<style>
    body {
        background-color: #FCF8E8;
    }
    h1{
        color: #937DC2;
        font-family: Lucida Bright;
        margin: auto;
        display: block;
        padding: 10px;
    }
    table{
        font-family: Lucida Bright;
        color: #937DC2;
        margin: auto;
        display: block;
        padding: 20px;
    }
</style>
<h1>Create Task</h1>  

    <form method="POST" >  
        {% csrf_token %}  
        <table>  
            <tr>
                <td>Title: </td>
                <td>{{form.title}}</td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td>{{form.description}}</td>
            </tr>
            <tr>  
                <td></td>
                <td><input class="btn btn-secondary" type="submit" name="submit" value="Post"/></td>  
            </tr>  
        </table>  
    </form>
<body>


{% if messages %}  
    <ul>   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
{% endif %}

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    body {
        background-color: #FCF8E8;
    }
    .login {
        font-family: Lucida Bright;
        color: #937DC2;
        font-size: medium;
        margin: auto;
        display: block;
        padding: 70px;
        align-items: center;
        justify-content: center;
        text-align: center;

    }
    table{
        margin: auto;
        align-items: center;
        justify-content: center;
        text-align: center;
        width: 100%;
        margin: auto;
        display: block;
        padding: 20px;
        border-radius: 25px;
    }
</style>

<body>
<div class = "login">
    <div class = "login container d-flex flex-column justify-content-center align-items-center">

    <h1>&#127775; Login &#127775; </h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table style="background-color: #FDDE74;">
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn btn-secondary" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>
</body>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

    {% block content %}  

    <style>
        body {
            background-color: #FCF8E8;
        }
        .login {
            font-family: Lucida Bright;
            color: #937DC2;
            font-size: medium;
            margin: auto;
            display: block;
            padding: 10px;
        }
        ul{
            font-size: 17px;
            color: #937DC2;
        }
        table{
            display: block;
            padding: 20px;
        }
    </style>

    <div class = "login">
        
        <h1>Formulir Registrasi</h1>  

            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input class="btn btn-secondary" type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

    </div>  
</body>
{% endblock content %}

todolist/templates/todolist_ajax.html
{% comment %} {% extends 'base.html' %}

{% block meta %} {% endcomment %}


{% comment %} {% extends 'base.html' %} {% endcomment %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}

<head>
    <title>Todolist</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
</head>
<style>

table, th, tr, td{
        font-family: Lucida Bright;
        color: #937DC2;
        border: 1px solid #937DC2;
        font-size: small;
        text-align: center;
        padding: 5px;
        background-color: #FFE6F7;
        background-image: linear-gradient(315deg, #FFE6F7 0%, #FFFFFF 74%);
        margin: 0 auto;

    }
    body {
      font-family: Lucida Bright;
      color: #937DC2;
      font-size: large;
      background-color: #FCF8E8;
    }
    h1{
        margin: 25px;
    }
    .body {
        padding-top: 16px;
        padding: 16px;
        font-family: Lucida Bright;
        font-size: 16px;
        color: #937DC2;

    }
    button {
        border-radius: 30px;
        background-color: #fdfdfc ;
        border: 2px solid #202121;
        padding: 5px 10px;
        font-family: Lucida Bright;
        font-size: 16px;
        margin: 7px 3px;
        color: #937DC2;
    }
 </style>

  <body>
    <div style="align-items: center;"class="wrapper" id="header">

        <div class="header pl-8">
            <div class="d-flex">
              <div class="mr-auto mb-auto mt-auto">
                <h1 class="primary-heading">&#128221; Todolist</h1>
              </div>
              <div class="p-3">
                <p>{{ username }}</p></div>
              </div>
            </div>
        </div>

        <div class="separator" style="padding:1px ;" ></div>

        <div class="body">

            <div class="modal" tabindex=-1 id="modalAddTask">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Task</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="POST" id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="modal-body">

                                <input id="title-controller" type="text" name="title" placeholder="Title" required>
                                <input id="description-controller" type="text" name="description" placeholder="Description" required>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                            <button id="button" type="submit" class="btn btn-secondary">Save</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    
    <br>
    <div class="d-flex justify-content-center align-items-center gap-3 responsive-container">
    {% for card in list_data %}
    <p class="card-text">{{ card.description }}</p>
          <a href="{% url 'todolist:delete' card.id %}" input class="btn btn-secondary">Delete</a></button> 
      </div>
    </div>
    {% endfor %}
  </div>

    <table id="table" style="border: 1px solid #937DC2;"></table>
    <button type="button" data-bs-toggle="modal" data-bs-target="#modalAddTask">Add Task</button>
    <button style="background-color: #a8a8a8;"><a style="color: #000000;"href="{% url 'todolist:logout' %}", class="custom-alert-button">Logout</a></button>

    
    <script>
        async function getTodolist(){
          return fetch("{% url 'todolist:show_json' %}").then((res) => res.json())
        }
        async function refreshTodolist(){
          document.getElementById("table").innerHTML=""
          const todolist = await getTodolist()
          let htmlString = `<tr>
            <th>Title</th>
            <th>Description</th>
            <th>Date</th>
          </tr>`
          todolist.forEach((item) => {
            htmlString += `\n<tr>
              <th>${item.fields.title}</th>
              <th>${item.fields.description}</th>
              <th>${item.fields.date}</th>
            </tr>` 
          })
          document.getElementById("table").innerHTML = htmlString
        }
    
        function addTodolist(){
          fetch("{% url 'todolist:submit_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
          }).then(refreshTodolist)
          return false
        }
    
        document.getElementById("button").onclick = addTodolist
        refreshTodolist()
      </script>
    
  </body>
  
  {% endblock content %}